version: "3"
services:
  frontend:
    hostname: frontend
    image: frontend:1.0
    ports:
      - "8080:8080"
    links:
      - backend
  backend:
    hostname: backend
    image: backend:1.0
    command: python server/app.py runserver 0.0.0.0:5000	
    ports:
      - "5000:5000"


